In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("clean_airBnb.csv")
df

,Unnamed: 0,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked
0,0,1000,Delhi,Apartment,5412.0,3.8,211.000000,9,Host_23,302,2025-08-05
1,1,1001,Mumbai,Apartment,7670.0,4.3,214.000000,9,Host_166,332,2025-12-26
2,2,1002,Ahmedabad,Villa,3813.0,4.3,1100.000000,7,Host_88,142,2025-03-21
3,3,1003,Goa,Loft,4204.0,3.9,133.711275,6,Host_166,135,2025-01-23
4,4,1004,Chennai,House,9020.0,5.0,93.000000,15,Host_221,185,2025-10-23
...,...,...,...,...,...,...,...,...,...,...,...
943,975,1975,Delhi,Loft,6764.0,4.3,165.000000,12,Host_47,98,2025-05-13
944,976,1976,Ahmedabad,Loft,3348.0,3.7,149.000000,7,Host_32,141,2025-02-02
945,977,1977,Pune,Apartment,7083.0,3.5,134.000000,2,Host_3,31,2025-05-17
946,978,1978,Mumbai,Loft,5656.0,4.1,137.000000,9,Host_247,136,2025-09-06
947,979,1979,Chennai,Studio,3437.0,3.8,210.000000,6,Host_81,122,2025-07-04

In [3]:
df.corr(numeric_only=True)

,Unnamed: 0,listing_id,price,rating,reviews,minimum_nights,availability_days
Unnamed: 0,1.000000,1.000000,0.030322,0.017510,-0.044449,-0.006130,-0.036860
listing_id,1.000000,1.000000,0.030322,0.017510,-0.044449,-0.006130,-0.036860
price,0.030322,0.030322,1.000000,0.031439,0.018245,0.029804,-0.022015
rating,0.017510,0.017510,0.031439,1.000000,0.013795,0.006975,-0.016943
reviews,-0.044449,-0.044449,0.018245,0.013795,1.000000,0.021092,0.028601
minimum_nights,-0.006130,-0.006130,0.029804,0.006975,0.021092,1.000000,0.012207
availability_days,-0.036860,-0.036860,-0.022015,-0.016943,0.028601,0.012207,1.000000

In [4]:
# if(rating > 4.6):
#     print(Price)

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
# y = mx + c : multiple features , = c + m1x1 + m2x2 + m3x3

In [7]:
# x : features (independent data)
# y : dependent data , predict

In [8]:
X = df[[
    "rating",
    "reviews",
    "availability_days"
]]
y = df["price"]

In [9]:
 # 23,45,56,67       , train  67 : 98 - 100 : 2
# 55, 89, 92, 100

In [1]:
4, 4.5, 3.5
34000, 45000, 27000
# m,c 
# 3.5 : 26500 - 500
# 3.7, 28000

(34000, 45000, 27000)

In [2]:
# 55= m*23 + c
# 89 = m*45 + c
# m = 2.3 , c = -34
# y = 2.3*56  -37
# y = 95

In [12]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 42)

In [13]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = model.predict(X_test)
y_pred

array([5603.54680122, 5685.57877898, 5640.24508354, 5863.01144067,
       5680.77584389, 5657.75994778, 5703.43032865, 5891.1294126 ,
       5846.73252681, 6002.62473691, 5987.55426082, 5743.09168393,
       5865.62286574, 5848.57053801, 5881.20159988, 5680.58516319,
       5641.19559054, 5798.66220605, 5862.53408807, 5679.0274248 ,
       5649.85453766, 5733.76253921, 5811.03267391, 6032.42734387,
       5680.90953431, 5908.78233245, 5575.3810614 , 5814.23272677,
       5726.05745532, 5815.27336696, 5778.37780129, 5774.30533709,
       5955.29771973, 5905.97440526, 5670.17451395, 5792.68270285,
       6024.29803695, 5799.96587438, 5504.13727017, 5764.86144305,
       5625.46969634, 5798.40187305, 5700.93994221, 5799.1280256 ,
       5711.94948716, 5770.98447332, 5733.2855241 , 5967.14766208,
       5797.67962804, 5623.29087471, 5668.10226481, 5732.93676455,
       5879.73846965, 5959.89350846, 5749.76491871, 5811.57326949,
       5516.1606017 , 5832.54955491, 5692.46654182, 5707.08246711,
       5663.75665907, 5937.29493183, 5511.94903635, 5662.91522636,
       5644.81867449, 5820.86703381, 5838.01473848, 5918.68907637,
       5639.72562994, 5905.70779319, 5921.02898312, 5501.71514275,
       5713.07422532, 5838.02048671, 5707.43430611, 5871.46037945,
       5712.67451073, 5752.3569348 , 5939.42745427, 5731.39600655,
       5677.92126755, 5943.74570191, 5931.74123828, 5849.27773923,
       6006.11767778, 5501.71236419, 5573.35322394, 6082.19920685,
       5489.00101271, 5855.68768158, 5792.6939716 , 5645.45109968,
       5848.58369428, 5700.02589775, 5860.08011735, 5913.94259047,
       5934.61194057, 5841.76275836, 5916.46280021, 6039.41488542,
       5941.59890445, 5700.88627156, 5937.36673819, 5755.19970132,
       5667.47593782, 5938.45696061, 5729.2443519 , 5852.71010589,
       5485.17984002, 5529.21391895, 5844.83429135, 5798.00898884,
       5886.67693346, 5913.76965894, 5784.61863621, 5755.17118789,
       5680.67309549, 5557.2095058 , 5637.90243482, 5742.18527523,
       5790.88119079, 5685.42255106, 5930.49784326, 5850.3942742 ,
       5888.02747865, 5734.05191648, 5746.23937599, 5840.78786293,
       5672.91781511, 5697.04727652, 5830.95813253, 5700.77144905,
       5595.15338402, 5791.09680099, 5418.42575926, 6036.75705137,
       5502.03434331, 5768.62041832, 5780.51773177, 5956.35206751,
       5857.09413489, 5645.93632821, 5910.41430579, 5825.07678483,
       5959.30032439, 5800.14289433, 5827.59703115, 5827.77073147,
       5566.9285021 , 5591.3078229 , 6037.03844293, 5752.11142813,
       5653.99464662, 5807.22411642, 5769.93207236, 5864.63539171,
       5767.86116968, 5697.69659643, 5589.56106363, 5703.57308693,
       5567.11127027, 5807.59972958, 5650.67598373, 5712.97346034,
       5835.80165518, 5813.41073962, 5964.95213684, 5939.32937196,
       5779.60912218, 5682.73110621, 5782.95795832, 5563.03852931,
       5508.19932006, 5615.63093467, 5713.36469497, 5803.64324324,
       5956.34111213, 5747.94091822, 5601.52111559, 5694.43635592,
       5731.55932915, 5715.01939693, 5613.69407237, 5862.96861563,
       5555.40763354, 5899.14111845, 5645.70806622, 5699.70804364,
       5860.93915494, 5831.55193087])

In [15]:
result = pd.DataFrame({
    "Actuall" : y_test,
    "Predict" : y_pred
})
# error = result["Actuall"] - result["Predict"]  not needed

In [16]:
# mae , mse, rmse, r2_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [17]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)
print("mae : ", mae)
print("mse : ", mse)
print("rmse : ", rmse)
print("r2 : ", r2)

mae :  2050.53255912301
mse :  6858333.538025149
rmse :  2618.842022349792
r2 :  -0.009844131187482175

In [18]:
model.coef_

array([169.39429333,   0.19179944,  -1.06174559])

In [19]:
model.intercept_

np.float64(5223.747168532429)

In [20]:
model.predict([[5	,250	,100]])

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([6012.49393614])

In [21]:
df.head(1)

,Unnamed: 0,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked
0,0,1000,Delhi,Apartment,5412.0,3.8,211.0,9,Host_23,302,2025-08-05