In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("iris.csv")
df
# df["Sprcies"].unique()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor

In [3]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()

y = le.fit_transform(df['Species'])
from sklearn.model_selection import train_test_split

y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
X = df[[
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm"
]]

# y = df["Species"]

In [5]:
poly = PolynomialFeatures(degree = 2)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size= 0.2, random_state = 42)

In [7]:
poly_train_X = poly.fit_transform(X_train)
poly_test_X = poly.transform(X_test)
poly_test_X

array([[1.000e+00, 6.000e+00, 2.700e+00, ..., 2.601e+01, 8.160e+00,
        2.560e+00],
       [1.000e+00, 5.500e+00, 2.300e+00, ..., 1.600e+01, 5.200e+00,
        1.690e+00],
       [1.000e+00, 5.900e+00, 3.200e+00, ..., 2.304e+01, 8.640e+00,
        3.240e+00],
       ...,
       [1.000e+00, 5.200e+00, 4.100e+00, ..., 2.250e+00, 1.500e-01,
        1.000e-02],
       [1.000e+00, 5.600e+00, 2.700e+00, ..., 1.764e+01, 5.460e+00,
        1.690e+00],
       [1.000e+00, 5.200e+00, 2.700e+00, ..., 1.521e+01, 5.460e+00,
        1.960e+00]], shape=(80, 15))

In [8]:
model = LinearRegression()
model.fit(poly_train_X, y_train)

LinearRegression()

In [9]:
y_pred = model.predict(poly_test_X)
y_pred

array([ 1.33397509e+00,  1.13163159e+00,  1.04927652e+00, -5.01152148e-02,
       -1.04901854e-01,  3.02004524e-02, -2.01488615e-01,  1.02604070e+00,
       -4.04521102e-03,  9.65753070e-03,  6.91658250e-02,  6.40611808e-02,
        5.11603536e-01, -1.92062691e-01,  9.34673431e-01, -3.87561197e-02,
        9.75225029e-01,  1.23687964e+00, -1.13685952e-02, -6.57262068e-02,
        9.48243002e-01,  9.44075264e-01,  6.20315113e-02, -2.80262649e-02,
        1.00731874e+00, -1.15922929e-01, -5.30017149e-02,  1.01171034e+00,
       -2.73905371e-02,  1.31409021e+00, -5.71333195e-02,  1.67143272e-02,
        8.52024087e-01,  2.27262393e-02,  8.87038097e-01,  1.98338067e-02,
        1.05893062e+00,  9.53770748e-01, -1.06151803e-01, -1.33909140e-01,
        2.52764231e-02, -2.73905371e-02,  1.80087985e-02,  7.53144809e-01,
        1.94838697e-02, -5.35120150e-02,  9.28598946e-01,  6.25202911e-02,
        7.53688175e-01, -7.34264474e-02, -3.02416440e-01,  4.98048315e-02,
        7.68190313e-03,  8.82228404e-04,  4.91336090e-02,  1.17095324e+00,
       -2.91989439e-02,  7.49377499e-01, -2.89522610e-02,  1.14073432e+00,
        9.92415275e-01,  1.07129502e+00,  1.13785102e+00, -2.21590117e-01,
        8.36582950e-01,  5.96911796e-01, -2.23221155e-01,  1.05124855e+00,
        1.00654207e+00,  9.98124012e-01,  8.06422090e-01, -5.82822364e-01,
        8.63336708e-01, -2.68188701e-02,  3.53761120e-01,  9.21140249e-01,
        9.91780807e-01, -5.97244363e-01,  1.13079962e+00,  1.01941567e+00])

In [10]:
result = pd.DataFrame({
    "actuall" : y_test,
    "predicted" : y_pred
})
result

    actuall  predicted
0         1   1.333975
1         1   1.131632
2         1   1.049277
3         0  -0.050115
4         0  -0.104902
..      ...        ...
75        1   0.921140
76        1   0.991781
77        0  -0.597244
78        1   1.130800
79        1   1.019416

[80 rows x 2 columns]

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [12]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)
print("mae : ", mae)
print("mse : ", mse)
print("rmse : ", rmse)
print("r2 : ", r2)

mae :  0.11538164827087391
mse :  0.032488065804221374
rmse :  0.18024446123035617
r2 :  0.8697220418878341

In [13]:
for i in range(1, 6):
    poly = PolynomialFeatures(degree = i)
    poly_train_X = poly.fit_transform(X_train)
    poly_test_X = poly.transform(X_test)
    model = LinearRegression()
    model.fit(poly_train_X,y_train)
    y_pred = model.predict(poly_test_X)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse**0.5
    r2 = r2_score(y_test, y_pred)
    print("mae : ", mae)
    print("mse : ", mse)
    print("rmse : ", rmse)
    print("r2 : ", r2)
    print("="*30)

mae :  0.07890544638366462
mse :  0.011499793762647
rmse :  0.1072370913567083
r2 :  0.953885538796403
==============================
mae :  0.11538164827087391
mse :  0.032488065804221374
rmse :  0.18024446123035617
r2 :  0.8697220418878341
==============================
mae :  0.09319181581329822
mse :  0.020841858450944502
rmse :  0.14436709615055815
r2 :  0.9164236252593704
==============================
mae :  0.0769728970664137
mse :  0.01375457290817173
rmse :  0.11727989132059993
r2 :  0.9448438179120933
==============================
mae :  0.08995024039203998
mse :  0.019582914203346728
rmse :  0.13993896599355996
r2 :  0.9214720232447249
==============================