In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("clean_airBnb.csv")
df

,Unnamed: 0,listing_id,city,property_type,price,rating,reviews,minimum_nights,host,availability_days,last_booked
0,0,1000,Delhi,Apartment,5412.0,3.8,211.000000,9,Host_23,302,2025-08-05
1,1,1001,Mumbai,Apartment,7670.0,4.3,214.000000,9,Host_166,332,2025-12-26
2,2,1002,Ahmedabad,Villa,3813.0,4.3,1100.000000,7,Host_88,142,2025-03-21
3,3,1003,Goa,Loft,4204.0,3.9,133.711275,6,Host_166,135,2025-01-23
4,4,1004,Chennai,House,9020.0,5.0,93.000000,15,Host_221,185,2025-10-23
...,...,...,...,...,...,...,...,...,...,...,...
943,975,1975,Delhi,Loft,6764.0,4.3,165.000000,12,Host_47,98,2025-05-13
944,976,1976,Ahmedabad,Loft,3348.0,3.7,149.000000,7,Host_32,141,2025-02-02
945,977,1977,Pune,Apartment,7083.0,3.5,134.000000,2,Host_3,31,2025-05-17
946,978,1978,Mumbai,Loft,5656.0,4.1,137.000000,9,Host_247,136,2025-09-06
947,979,1979,Chennai,Studio,3437.0,3.8,210.000000,6,Host_81,122,2025-07-04

In [3]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [4]:
X = df[[
    "rating",
    "reviews",
    "minimum_nights",
    "availability_days"
]]
y = df["price"]

In [5]:
poly = PolynomialFeatures(degree = 2)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size= 0.2, random_state = 42)

In [7]:
poly_train_X = poly.fit_transform(X_train)
poly_test_X = poly.transform(X_test)
poly_test_X

array([[1.00000e+00, 3.20000e+00, 8.40000e+01, ..., 1.96000e+02,
        2.35200e+03, 2.82240e+04],
       [1.00000e+00, 3.80000e+00, 1.70000e+02, ..., 4.90000e+01,
        1.41400e+03, 4.08040e+04],
       [1.00000e+00, 3.90000e+00, 2.80000e+01, ..., 4.90000e+01,
        1.64500e+03, 5.52250e+04],
       ...,
       [1.00000e+00, 4.20000e+00, 5.00000e+00, ..., 6.40000e+01,
        4.00000e+02, 2.50000e+03],
       [1.00000e+00, 5.00000e+00, 1.74000e+02, ..., 4.90000e+01,
        1.19000e+03, 2.89000e+04],
       [1.00000e+00, 3.60000e+00, 6.40000e+01, ..., 2.25000e+02,
        5.04000e+03, 1.12896e+05]], shape=(759, 15))

In [8]:
model = LinearRegression()
model.fit(poly_train_X,y_train)

LinearRegression()

In [9]:
y_pred = model.predict(poly_test_X)
y_pred

array([ 4411.07479957,  5136.77485335,  6034.51625602,  7733.18179961,
        5682.51537605,  5283.58635843,  5061.10864445,  6230.16820279,
        6424.30097116,  6676.96977882,  7007.8844167 ,  5512.47007046,
        5887.70497648,  5892.53633972,  6840.80522359,  5174.90033328,
        5935.6293485 ,  6005.05852854,  5521.28299247,  6409.34115273,
        6566.54562856,  5712.47361364,  5801.44828512,  6769.54713576,
        6698.87642675,  5919.78370664,  6401.22819251,  5606.65882703,
        4462.01944138,  5667.2024837 ,  5621.4502019 ,  6264.70236769,
        6780.89162139,  5943.37290379,  6696.26981573,  6297.96308322,
        7203.11328107,  6184.56635179,  6285.3035036 ,  4809.35444382,
        5924.38343115,  5674.87150505,  5955.44316086,  5784.96880737,
        5890.92741948,  6642.17996818,  6174.15299754,  6998.48457129,
        5097.2678714 ,  5835.15348462,  6038.21149316,  7032.18820969,
        6038.25892416,  6515.78578901,  6619.55372727,  6069.07065055,
        7385.01161673,  6129.64112717,  5671.52747216,  4745.40157727,
        7181.0954956 ,  6594.50116914,  4797.45028303,  5867.6849405 ,
        6116.73811119,  6481.18671795,  5922.55910352,  6287.99733843,
        5045.12993797,  7374.53512117,  6130.7510037 ,  4907.18076771,
        6284.21526447,  5754.65240986,  5796.8442742 ,  6284.77662365,
        5592.78355937,  5529.70632469,  6329.56952786,  6663.37002002,
        7606.18769838,  6342.0933924 ,  6462.92740776,  5899.72684505,
        6950.45447533,  6184.45548834,  4165.19439202,  7735.74573548,
        5388.02392805,  6633.4209595 ,  6338.94066764,  5224.49285632,
        6181.82329715,  6675.87295082,  5926.45631044,  6105.08075931,
        6538.63861954,  6648.14314606,  6790.33504357,  7474.61845048,
        6292.49600993,  6269.30679343,  6314.47908091,  5290.27103197,
        5749.18455147,  6013.60895435,  6691.7364393 ,  7460.26157322,
        5593.05546433,  5998.23648158,  7962.48518144,  5922.62157471,
        6269.4140569 ,  5934.02019877,  5927.37921157,  5583.81920347,
        5404.8334452 ,  3659.83394365,  5188.89777464,  5498.61146977,
        5579.91116676,  6346.81062803,  6028.07748743,  5578.54186274,
        5949.89557818,  6258.19265767,  5494.31616482,  5906.1024985 ,
        5736.61189837,  4933.19519796,  6348.92999802,  6024.99867698,
        5138.34657829,  5460.18863135,  6893.86996875,  7026.27680859,
        5824.55014354,  6399.38675781,  5459.55059927,  6587.87618385,
        6009.83632655,  6070.33499773,  6475.40977118,  5864.35107154,
        6326.03153086,  5463.54062417,  5874.90647883,  5954.99602852,
        6033.98117894,  5512.35957724,  6964.52382168,  5306.08198212,
        5313.72441712,  6000.08885768,  5640.04780509,  6090.11058593,
        5793.02295749,  7833.72322657,  5931.06201173,  5378.73938354,
        4848.7455377 ,  6410.48765188,  6877.56078243,  4635.88997846,
        5906.72454387,  5648.86239642,  6649.77012918,  7045.49580481,
        7458.19328559,  5679.47003268,  5483.35262057,  6467.69294731,
        5662.24118766,  6444.73946804,  6567.43355459,  5810.64838052,
        6790.08376322,  5237.8840964 ,  5816.66842084,  5180.8206456 ,
        5568.16785112,  5229.5480877 ,  5532.95198121,  5929.47719255,
        5894.21606449,  6173.27758743,  6332.14637483,  5848.38626254,
        6203.95841001,  6274.43656036,  5811.64605742,  4959.38810204,
        5145.24206893,  5593.6993193 ,  6165.03119218,  5890.84591161,
        5155.41094515,  6498.7463461 ,  6502.75917121, 28673.62734994,
        6407.37282252,  4866.85910077, 75513.62134323,  6966.17225423,
        5871.81877388,  6448.70010023,  6065.16963313,  5714.53478597,
        4982.18780803,  6649.48427017,  5705.05411648,  5992.49787854,
        7186.91304966,  5742.7623225 ,  6703.06012485,  5953.82683763,
        6197.66596929,  6172.52751342,  4887.5605788 ,  6826.71724855,
        5918.44561169,  6213.48058622,  5647.08021161,  4753.46877568,
        6279.17191992,  5319.17354276,  6839.23541449,  6117.06910659,
        5441.00226641,  5123.67968747,  5745.96678943,  6417.29068918,
        5418.03731403,  5615.84950949,  6201.63926179,  6008.30102601,
        6136.81383991,  8678.09876522,  6401.0242109 ,  6148.5179827 ,
        6275.80483892,  6226.45412588,  6175.40567035,  5811.18145049,
        5528.12524286,  5111.37694249, 54457.11224529,  5906.94262762,
        6392.16413121,  5710.04536669,  6208.09971507,  6101.953014  ,
        6099.24481957,  5568.40115804,  5581.29771906,  6320.24136544,
        5632.80533531,  5100.59424506,  5086.07217438,  6434.55272924,
        6187.58259145,  7268.20737581,  6282.77588453,  6254.24403209,
        7213.90591425,  5514.82053371,  5332.72653228,  6094.00447285,
        5937.71845042,  6924.98004844,  5656.30088196,  5687.34618441,
        6868.48558594,  6792.66317188,  6192.26003835,  6217.75913396,
        5985.99687776,  6265.59809144,  5603.3435226 ,  5686.10868611,
        5509.03106722,  7588.06251645,  5771.53142592,  6160.21147386,
        4587.95767201,  6518.69564001,  7286.3184951 ,  6825.3591697 ,
        5626.93410241,  6484.54788715,  6186.60710559,  5895.89859762,
        4766.51685189,  6421.02047932,  5222.86043386,  4725.76568182,
        5999.10509064,  5446.60501644,  5921.81854058,  6375.65181657,
        5367.65596732,  5874.69466025,  8343.01008839,  5923.79915197,
        5385.81459155,  6160.48000716,  6391.10984486,  6303.4526784 ,
        5698.83514642,  6227.49803938,  5257.32197014,  5670.44148476,
        6199.40436545,  4835.14534761,  5321.36978139, 39953.89441752,
        5735.08877163,  5271.09301599,  5257.26967911,  4659.57005353,
        5717.99677281,  6591.01835568,  5595.37524294,  6456.32380186,
       54671.68829201,  7342.11746862,  5568.52766545,  5764.80744201,
        6378.68926335,  5140.05751448,  5888.67823211,  6900.16716695,
        6338.05409812,  5290.12220595,  5628.87348036,  6533.28644389,
        5721.92246379,  5965.02891563,  5377.83668444,  5320.76045568,
        5540.22005643,  5945.99300181,  5402.23161851,  6080.09017176,
        5685.70076328,  6188.55364556,  5599.05008662,  5499.67274027,
        6149.29547033,  6192.36339018,  5411.08446657,  6817.6320912 ,
        5494.21566451,  5604.52916741,  6949.05750817,  5790.02264912,
        7835.90376654,  6553.31173417,  5996.53248906,  5566.73554835,
        6033.57316996,  6517.9503235 ,  5559.2123696 ,  6145.77990823,
        5814.38482687,  7588.43789686,  5532.70905974,  6959.55235972,
        5559.6728357 ,  7341.02349272,  6451.82398858,  6997.58026758,
        5782.44666964,  5955.32823786,  8177.93888302,  6705.16660773,
        7945.73514057,  5487.58230409,  7212.47483841,  5379.86192459,
        6561.31213626,  6098.43521222,  6129.0427184 ,  6907.79550395,
        6932.00532136, 18481.45478193,  5415.36173187,  6157.17549953,
        6386.34142145,  5738.95110567,  6466.979314  ,  6789.02480267,
        6910.12692204,  5945.04522272,  5689.6466844 ,  8042.83314275,
        5582.22392224,  5822.33012648,  5376.85895285,  7121.9661426 ,
        6326.03804622,  6153.49059819,  5909.435081  ,  6595.18509293,
        5030.42162403,  6305.32225497,  5735.10526214,  7224.41331506,
        6646.65231146,  6050.46764218,  6111.28783365,  5560.58748016,
        6187.59265822,  6776.44263284,  4989.83363628,  6495.56823906,
        6697.13546276,  5615.48148573,  5642.0884513 ,  5441.69879336,
        6020.8910061 ,  6593.74026246,  6696.76357228,  5745.8665949 ,
        5872.93074644,  5328.98317778,  6450.46494083,  5578.70660516,
        6732.07623121,  6816.57967595,  5073.00000615,  6290.89401523,
        5801.98352351,  6709.47377579,  5957.0673374 ,  7055.77253642,
        6098.40292941,  6120.86390217,  5230.3632549 ,  5684.85848989,
        6167.18888818,  5557.07453535,  6419.66471755,  5754.08978889,
        6705.1375336 ,  5141.30364832,  6291.41304271,  7354.48214899,
        5664.67848808,  5555.81039722,  6816.57744998, 30745.49104272,
        5453.24263668,  5531.48463504,  7677.18770656,  5476.73543592,
        5883.80266531,  7025.02505334,  7190.97832381,  5251.63638779,
        5803.25394497,  5510.50988372,  5945.27815842,  5911.0633905 ,
        5627.56332073,  6666.53281956,  5103.69462453,  6773.54444215,
        6062.73205691,  4755.85996008,  4875.12348151,  5674.93343915,
        7027.91146631,  5603.7296981 ,  6729.15153825,  4503.53522057,
        5852.96114833,  6320.28857784,  5646.88215001,  7552.26439161,
        6287.91633028, 87993.43939203,  7390.90019379,  6285.39527851,
        5549.42068117,  6487.09470287,  7479.04089226,  5310.06180589,
        5715.040606  ,  7516.21861674,  6069.70982381,  6019.97830322,
        6497.44620284,  6468.42544767,  5552.73328337,  6145.62556013,
        5737.31850458,  6567.89716347,  6941.48584809,  6522.55336081,
        5986.55260217,  5116.03783731, 81813.05917803,  6519.25596989,
        5756.50943488,  7303.00458595,  5543.93605038,  6050.12695494,
        5682.29017582,  5540.66605133,  7097.38056521,  6374.344037  ,
        5610.44367916,  6828.25987588,  6851.96329735,  6327.76190333,
        6554.69409744,  6896.88601353,  6253.60415707,  6394.6898042 ,
        4641.57761038,  7574.30598141,  7353.84864042,  5852.00981833,
        5518.60374821,  6566.31926433,  6586.73524505,  5671.86118369,
        6025.1804814 ,  8505.11097011,  7232.92301433,  5311.56346888,
        5419.15574019,  6543.60823629,  6757.86010765,  5915.58995109,
        5975.23203759,  6843.56631611,  5253.28720977,  5821.17217745,
        5275.16965682,  5769.00572367,  6311.79765558,  6394.21619208,
        5920.33898367,  6623.79560203,  6711.575871  ,  5526.59746603,
        5265.80002225,  6416.97214893,  7630.95189415,  5832.661178  ,
        7013.50238907,  5311.63172532,  5562.53420205,  6154.3935348 ,
        6467.56518014,  5515.24942788,  6784.88376468,  5924.00769402,
        5734.72188285,  5740.57690613,  5589.64235354,  6293.07316973,
        5152.70954226,  6018.53441523,  5754.45176253,  5746.18593986,
        6639.04646489,  5953.11672987,  5621.71994739,  5466.07803824,
        7026.06249011,  5814.86675699,  7334.96536509,  5842.76066766,
        5147.14681485,  6003.49263047,  6423.57486776,  6240.79523674,
        5494.03549201,  6319.28787797,  6242.27730029,  5034.35354309,
        6762.22649286,  6518.00831687,  6272.44993477,  6701.42930256,
        6858.80975447,  5900.21200784,  6067.83495784,  5303.44948462,
        4695.06266851,  5922.43259973,  6350.33593638,  5437.77768997,
        6792.5974609 ,  6517.52325653,  4883.74526676,  6597.97265782,
        6259.80229113,  6966.15737182,  5947.91243975,  6822.7348464 ,
        5862.72532136,  6238.3498805 ,  7635.84345019,  5278.14179246,
        6239.33179316,  6418.00053342,  6499.82758219,  6359.48012689,
        6540.16390517,  5925.98120372,  5792.68222884,  6573.30602697,
        6913.39805815,  7215.6332019 ,  7625.19173005,  5315.26194286,
        6382.15656117,  5536.38315116,  5832.8774598 ,  6487.63857103,
        6592.87512024,  7015.8340733 ,  6605.51199253,  6953.37058735,
        4939.13213903,  6628.97427672,  6071.78806255,  6613.48859643,
        5580.79994895,  6252.2457209 ,  6842.06008394,  5754.43836191,
        6191.78183739,  7031.13876262,  5940.89621646,  6126.23489654,
        5937.76376772,  6717.82029287,  5372.57829528,  4916.19155191,
        6640.08289547,  7901.60950637,  6298.26734976,  5385.76669286,
        6097.81142922,  6217.04211274,  5705.53953717,  5769.92188971,
        5592.28883176,  6444.71337431,  5150.50648864,  5299.30684429,
        5661.73423637,  7236.46274517,  6733.08501833,  5938.50444891,
        5928.04617144,  5821.15604744,  6901.6058672 ,  6274.89241568,
        5812.00621289,  7027.53182931,  6303.58820874,  6045.44705608,
        6407.56377434,  5565.3211362 ,  5945.38107514,  6270.97576117,
        6019.84228689,  5434.8634264 ,  6633.55023211,  7276.61155748,
        6670.79732228,  6053.0955912 ,  5237.0555929 ,  7089.08229029,
        6664.07770951,  5618.0722693 ,  5678.91016111,  5160.42083949,
        5713.492553  ,  6438.02649083,  5261.50836205,  5747.35591396,
        6828.46670856,  6742.6668425 ,  6047.52287664,  5272.69177585,
        5382.61173699,  7084.50149019,  5966.78367368,  7204.73984311,
        7828.65893052,  5705.74159929,  6606.32496955,  5660.56978355,
        5619.04550057,  6857.45223851,  5483.92072088,  6112.6828853 ,
        7342.23355279,  7616.53492393,  5748.20954277,  5909.29312545,
        6414.47265872,  5441.25104606,  6686.77410016,  6173.46863545,
        6905.05291028,  6568.25352701,  5840.44942313,  6802.53175781,
        6850.32676806,  5269.01518022,  5413.81117035,  5592.40435055,
        5946.52031615,  6302.44443873,  4753.76065382,  5010.33116383,
        7044.55600506,  5906.3209756 ,  6171.88890567,  4835.82688001,
        5660.77836451,  6457.07170968,  9731.84553544,  5956.98459496,
        5799.4918751 ,  7661.04534727,  6163.77388312,  5946.51263004,
        6477.39374018,  5669.76357792,  6246.90398447,  6636.86481026,
        5822.61096426,  5939.19619742,  5209.3611184 ,  7001.35541283,
        7066.83215268,  8474.89819951,  5966.766007  ,  6366.01341111,
        5599.79343372,  7318.66032912,  6326.9862019 ,  6521.57843218,
        7048.33600607,  6589.59517234,  6305.29489625,  5529.98749426,
        6394.20363268,  6527.56345316,  6023.57796181])

In [10]:
result = pd.DataFrame({
    "actuall" : y_test,
    "predicted" : y_pred
})
result

     actuall    predicted
589   5724.0  4411.074800
933   7374.0  5136.774853
139   2452.0  6034.516256
86    9563.0  7733.181800
39    5744.0  5682.515376
..       ...          ...
911   7973.0  6305.294896
619   3354.0  5529.987494
810   4498.0  6394.203633
645   7575.0  6527.563453
802   6009.0  6023.577962

[759 rows x 2 columns]

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [12]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)
print("mae : ", mae)
print("mse : ", mse)
print("rmse : ", rmse)
print("r2 : ", r2)

mae :  2704.5211900763056
mse :  39946245.13220764
rmse :  6320.3041961766085
r2 :  -4.864120717071831

In [13]:
for i in range(1, 6):
    poly = PolynomialFeatures(degree = i)
    poly_train_X = poly.fit_transform(X_train)
    poly_test_X = poly.transform(X_test)
    model = LinearRegression()
    model.fit(poly_train_X,y_train)
    y_pred = model.predict(poly_test_X)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse**0.5
    r2 = r2_score(y_test, y_pred)
    print("mae : ", mae)
    print("mse : ", mse)
    print("rmse : ", rmse)
    print("r2 : ", r2)
    print("="*30)

mae :  2142.039690493067
mse :  7281373.259970759
rmse :  2698.401982650242
r2 :  -0.06890776945892174
==============================
mae :  2704.5211900763056
mse :  39946245.13220764
rmse :  6320.3041961766085
r2 :  -4.864120717071831
==============================
mae :  12102.880542353041
mse :  12114808233.199203
rmse :  110067.28956960466
r2 :  -1777.457467242044
==============================
mae :  1124600.3402758294
mse :  179765409205607.4
rmse :  13407662.33187603
r2 :  -26389614.766052324
==============================
mae :  5216228.552714748
mse :  5764215197315966.0
rmse :  75922428.81596957
r2 :  -846188511.6967068
==============================