In [1]:
import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv("weather_forecast_data.csv")
df

      Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0       23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1       27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2       25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3       23.622080  74.367758    7.050551    67.255282   982.632013     rain
4       20.591370  96.858822    4.643921    47.676444   980.825142  no rain
...           ...        ...         ...          ...          ...      ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181  no rain
2496    27.558479  46.481744   10.884915    39.715133  1008.590961  no rain
2497    28.108274  43.817178    2.897128    75.842952   999.119187  no rain
2498    14.789275  57.908105    2.374717     2.378743  1046.501875  no rain
2499    26.554356  97.101517   18.563084    81.357508  1001.729176  no rain

[2500 rows x 6 columns]

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
df.columns

Index(['Temperature', 'Humidity', 'Wind_Speed', 'Cloud_Cover', 'Pressure',
       'Rain'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  2500 non-null   float64
 1   Humidity     2500 non-null   float64
 2   Wind_Speed   2500 non-null   float64
 3   Cloud_Cover  2500 non-null   float64
 4   Pressure     2500 non-null   float64
 5   Rain         2500 non-null   object
dtypes: float64(5), object(1)
memory usage: 117.3+ KB

In [6]:
X = df.drop("Rain", axis=1) 
y = df["Rain"]

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [10]:
y_pred = model.predict(X_test)
y_pred

array(['no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'rain', 'rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'no rain', 'no rain',
       'no rain', 'no rain', 'no rain', 'no rain', 'rain', 'no rain',
       'no rain'], dtype=object)

In [11]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.962

In [12]:
result = pd.DataFrame({
    "Actuall" : y_test,
    "Predict" : y_pred
})
result

      Actuall  Predict
1447  no rain  no rain
1114  no rain  no rain
1064     rain  no rain
2287  no rain  no rain
1537  no rain  no rain
...       ...      ...
2375  no rain  no rain
1609  no rain  no rain
596      rain     rain
84    no rain  no rain
2213  no rain  no rain

[500 rows x 2 columns]

In [13]:
accuracyScore = accuracy_score(y_test, y_pred)
accuracyScore

0.962

In [14]:
matrix = confusion_matrix(y_test, y_pred)
matrix

array([[434,   9],
       [ 10,  47]])

In [15]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

     no rain       0.98      0.98      0.98       443
        rain       0.84      0.82      0.83        57

    accuracy                           0.96       500
   macro avg       0.91      0.90      0.91       500
weighted avg       0.96      0.96      0.96       500